Task 10 Complete
JxckHind/NC-News-Backend pull request #9
Opened 2023-01-19 12:21 UTC by JxckHind

2023-01-19 16:04 UTC, xViolaine requested changes

2023-01-19 16:04 UTC, xViolaine commented on __tests__/app.test.js
> +            })
Paper is still a valid topic, it just doesn't have any articles - should respond with an empty array & a 200 :)

2023-01-19 16:04 UTC, xViolaine commented on models/news-models.js
> +        }
See comment at the corresponding test

2023-01-20 08:53 UTC, Hard-Luck approved these changes

2023-01-20 10:39 UTC, merged